### ISSUE TITLE
Including the build process within the project

### ISSUE THREAD

**Issue by mlampert84** [mandyr/stammbuch-visualisierung#3]
We need to set up a system for building the project where the build configuration is within the github project folder, and not only on someone's local computer.

There a few important parts to the build:
1) compiling scss to css.  I would suggest using npm for this, so that we have a package.json file and then can simple run 'npm run build', which would, among other things, compile the sass files.

2) I think we also need webpack for the build. I will look into this.

3) Putting the results of the build on the gh-pages branches so that our site is hosted via mandyr.github.io/stammbuch-visualisierung.  For putting the build onto gh-pages branch, we can either do this manually or automatically.  Manually is obviously simpler in the beginning, put we might make mistakes.  Here is a description of how one can do it automatically: h[ttps://gist.github.com/domenic/ec8b0fc8ab45f39403dd](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)

**Comment by mlampert84** [comment]
I looked into this further, and it seems that npm with webpack is the way to go. Basically, we can use an npm module ("node-sass-chokidar" or "node-sass") and a webpack file to convert scss to css.  React does this, for example, and I've something like it before, so I am happy to set this up.

Also, we definitely need something like webpack anyway since we have at least two .js files (the main.js for the overall webpage interactivity, and then a javascript file that takes care of the D3 visualization).  We will likely have more .js files - for example various files that perform calculations on the graph (i.e network), such as finding the shortest path between two nodes/people.

Does npm and webpack sound good?  If you have an alternative suggestion, let me know.

**Comment by mandyr** [comment]
Sure, let's use Webpack and npm. I'm familiar with both as well, so it should be easy to set it up.

**Comment by mlampert84** [comment]
Okay, great. I'll true to get this set up tomorrow.

**Comment by mlampert84** [comment]
Webpack config has now been included. Scss code is successfully transpiling into css.

There seems to be some original css files that I put into the folder: "src/css_OLD_DELETE?".  Can we delete these files? It looks to me like we can.

**Comment by mandyr** [comment]
Awesome! I'll update my local project this evening and check if the old css files are still necessary or if we can delete them.

**Comment by mlampert84** [comment]
Old css files have been deleted.
