### ISSUE TITLE
Host from gh-pages

### ISSUE THREAD

**Issue by mlampert84** [mandyr/stammbuch-visualisierung#5]
I've pushed the dist folder to gh-pages (git subtree push --prefix dist origin gh-pages), but the site, 
mandyr.github.io/stammbuch-visualisierung, is not showing anything.  Can you look at the "Settings" to make sure that the project is set to be hosted from gh-pages?

**Comment by mandyr** [comment]
It's working now! I changed the settings

**Comment by mlampert84** [comment]
Hmm - when I navigate to "mandyr.github.io/stammbuch-visualisierung" I get a 404.

**Comment by mandyr** [comment]
That's weird, it isn't working anymore... I swear it worked 30 min ago :smile: I'll take a look at it.

**Comment by mandyr** [comment]
Can you see if https://mandyr.github.io/stammbuch-visualisierung/index.html works for you?
Because that works, but without the index.html part it doesn't...

**Comment by mlampert84** [comment]
Indeed, that does work! Not sure why that is - since I thought gh-pages automatically serves index.html.

Thanks for fixing it!
